# Generated by Django 4.2 on 2025-04-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
    ]
